version: '2'

run:
  build-tags:
    - acceptance

linters:
  settings:
    lll:
      line-length: 80
      tab-width: 4
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - lll

formatters:
  enable:
    - gofumpt
    - golines
  settings:
    golines:
      max-len: 80
      tab-len: 4
      shorten-comments: true
